// One generated test per ROUTE_INVENTORY entry — Playwright's own native
// "loop to generate tests" pattern, per
// docs/architecture/phase-5a-technical-design.md §1.4, not 30 hand-authored
// files. Runs under the "desktop" Playwright project only — see
// playwright.config.ts's own comment for why.
//
// Each route's zero-"critical"/"serious"-violations assertion is this
// suite's actual release gate (Accessibility AC2). "moderate"/"minor"
// findings are never silently dropped and never fail the run — they are
// collected across every route and written, once, to a Markdown report
// under docs/testing/e2e/ as a named, owned backlog artifact (§1.3's own
// framing), via this file's own `test.afterAll` hook.
import fs from "node:fs"
import path from "node:path"

import { expect, test } from "@playwright/test"
import type { Result } from "axe-core"

import { checkAccessibility } from "../support/axe"
import { ADMIN_STORAGE_STATE, ORDINARY_STORAGE_STATE } from "../support/storage-state"
import { ROUTE_INVENTORY } from "../support/route-inventory"

interface ModerateMinorFinding {
  route: string
  label: string
  impact: string
  ruleId: string
  description: string
  nodeCount: number
}

const findings: ModerateMinorFinding[] = []

for (const route of ROUTE_INVENTORY) {
  test.describe(route.label, () => {
    test.use({
      storageState: route.requiresAdmin ? ADMIN_STORAGE_STATE : ORDINARY_STORAGE_STATE,
    })

    test(`${route.label} — zero critical/serious axe violations`, async ({ page }) => {
      await page.goto(route.path)
      // Wait for a stable landmark rather than a fixed timeout — every
      // authenticated route renders exactly one <main> (Accessibility AC9);
      // /login has no <main> wrapper of its own (see (auth)/layout.tsx), so
      // it waits on its sign-in form's Email field instead. Deliberately NOT
      // `getByRole("heading", ...)`: `CardTitle` (src/components/ui/card.tsx)
      // renders a plain `<div>`, not a real heading element, so waiting on a
      // heading role would time out before axe ever gets to run — this wait
      // condition must not assume page structure the a11y scan below is
      // itself the one responsible for verifying.
      if (route.path === "/login") {
        await expect(page.getByLabel("Email")).toBeVisible()
      } else {
        await expect(page.locator("main")).toBeVisible()
      }

      const results = await checkAccessibility(page)

      const criticalOrSerious = results.violations.filter((violation) =>
        ["critical", "serious"].includes(violation.impact ?? ""),
      )

      const moderateOrMinor = results.violations.filter((violation) =>
        ["moderate", "minor"].includes(violation.impact ?? ""),
      )
      for (const violation of moderateOrMinor) {
        findings.push({
          route: route.path,
          label: route.label,
          impact: violation.impact ?? "unknown",
          ruleId: violation.id,
          description: violation.description,
          nodeCount: violation.nodes.length,
        })
      }

      expect(
        criticalOrSerious,
        formatViolationsForAssertionMessage(criticalOrSerious),
      ).toHaveLength(0)
    })
  })
}

function formatViolationsForAssertionMessage(violations: Result[]): string {
  if (violations.length === 0) return ""
  return violations
    .map((v) => `[${v.impact}] ${v.id}: ${v.description} (${v.nodes.length} node(s))`)
    .join("\n")
}

test.afterAll(async () => {
  const reportPath = path.join(process.cwd(), "docs", "testing", "e2e", "accessibility-report.md")
  fs.mkdirSync(path.dirname(reportPath), { recursive: true })

  const generatedAt = new Date().toISOString()
  const lines: string[] = [
    "# Phase 5a — Accessibility Audit: Moderate/Minor Findings Backlog",
    "",
    `Generated by \`tests/e2e/accessibility/route-a11y.spec.ts\` (\`npx playwright test accessibility\`) on ${generatedAt}.`,
    "",
    "Per docs/architecture/phase-5a-technical-design.md §1.3 / Accessibility AC2: " +
      "zero critical/serious axe-core violations is this suite's release gate " +
      "(enforced by the test assertions themselves). Every moderate/minor " +
      "finding below is accepted, tracked debt — a named, owned backlog item, " +
      "not silently dropped and not blocking the release gate.",
    "",
  ]

  if (findings.length === 0) {
    lines.push("No moderate/minor findings on the most recent run.")
  } else {
    lines.push(`**${findings.length} moderate/minor finding(s) across the route inventory:**`, "")
    lines.push("| Route | Impact | Rule | Description | Nodes |")
    lines.push("|---|---|---|---|---|")
    for (const finding of findings) {
      lines.push(
        `| \`${finding.route}\` (${finding.label}) | ${finding.impact} | ${finding.ruleId} | ${finding.description} | ${finding.nodeCount} |`,
      )
    }
  }

  fs.writeFileSync(reportPath, lines.join("\n") + "\n")
})
